config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :topics do
  	member do
  		post :comments #topics對應多個comments, 應為複數 ！
  	end
  end
  root "topics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :topics
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :topic
	belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title, :content

	belongs_to :category
	belongs_to :user

	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :topics
  has_many :comments

  def is_creator?(topic)
  	topic.user == self
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :find_topic, only: [:show, :edit, :update, :destroy, :comments]
	before_action :authenticate_user!, except: [:index]

	def index
		@topics = Topic.page(params[:page]).per(10).order('created_at DESC')

		if params[:id]
      @topic = Topic.find(params[:id])
    else
      @topic = Topic.new
    end
		
	end

	def new
		@topic = Topic.new
		
	end

	def create
		@topic = Topic.new(topic_params)
		@topic.user = current_user

		if @topic.save
			redirect_to topics_path
		else
			render :new
		end
		
	end

	def show
		@comment = Comment.new
		@comments = Comment.all

		
	end

	def edit
		
	end

	def update
		if @topic.update(topic_params)
			redirect_to topic_path(@topic)
		else
			render :edit
		end

	end

	def destroy
		@topic.destroy

		redirect_to topics_path
		
	end

	def comments
		@comment = @topic.comments.new(comment_params)
		@comment.user = current_user
		@comment.save!

		redirect_to topic_path(@topic)
		
	end



	private

	def topic_params
		params.require(:topic).permit(:title, :content, :category_id, :user_id)
		
	end

	def comment_params
		params.require(:comment).permit(:description, :topic_id, :user_id)
		
	end

	def find_topic
		@topic = Topic.find(params[:id])
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MidtermTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    	<% if current_user %>
  	    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  	    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  	  <% else %>
  	    <%= link_to('註冊', new_registration_path(:user)) %> |
  	    <%= link_to('登入', new_session_path(:user)) %>
  	  <% end %>
  	  
  	  <p class="notice"><%= notice %></p>
  	  <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
 <ul>
   <% @topic.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
 </ul>
<% end %>

<%= simple_form_for @topic do |n| %>
	
	<div class="form-group">
    <%= n.input :title, input_html: { class: "form-control"} %>
   	<%= n.collection_select(:category_id, Category.all, :id, :name, prompt: "請選擇分類") %>
    <%= n.input :content, input_html: { class: "form-control"} %>
  </div>

	<%= n.submit 'POST', class: 'btn btn-warning' %>
	<%= link_to 'CANCEL', topics_path, class: 'btn btn-info' %>
 <% end %>

app/views/topics/edit.html.erb
<h2><%= @topic.title %></h2>

<%= render partial: 'form', locals:{button: 'UPDATE'} %>

app/views/topics/index.html.erb
<div class="header">
	<h1>寇汀災情支援網</h1>
	<subtitle>Coding Recue Network</subtitle>
</div>

<div class="new_post">
	<%= link_to 'POST', new_topic_path(@topic), class: 'btn btn-success' %>
</div>

<div class="pagination">
	<%= paginate @topics %>
</div>

<table class="table table-hover text-center">
	<tr>
		<th>類別</th>
		<th>標題</th>
		<th>建立日期</th>
		<th></th>
	</tr>
		<% @topics.each do |t| %>
	<tr>
			<td>【<%= t.category.name %>】</td>
			<td><%= link_to t.title, topic_path(t) %></td>
			<td><%= t.created_at.to_date %></td>
			<td>
				<% if current_user && current_user.is_creator?(t) %>
					<%= link_to 'EDIT', edit_topic_path(t), class: "btn btn-primary btn-sm" %>
					<%= link_to 'DEL', topic_path(t), method: :delete, data:{ confirm: 'Are you sure ?' }, class: "btn btn-danger btn-sm" %>
				<% end %>
			</td>
	</tr>
		<% end %>
</table>

<div class="pagination">
	<%= paginate @topics %>
</div>

app/views/topics/new.html.erb
<h2>Post an article</h2>

<%= render partial: 'form', locals:{button: 'POST'} %>

app/views/topics/show.html.erb
<h2><%= @topic.title %></h2>



<table>
	<tr>
		<th>類別</th>
		<td>【<%= @topic.category.name %>】</td>
	</tr>
	<tr>
		<th>建立日期</th>
		<td><%= @topic.created_at.to_date %></td>
	</tr>	
	<tr>
		<th>內容</th>
		<td><%= @topic.content %></td>
	</tr>
</table>

<%= link_to 'BACK', topics_path %>


<hr>
<% @comments.each do |c| %>
	<%= c.user.email %><br>
	<%= c.description %><br>
<% end %>

<%= simple_form_for @comment, url:comments_topic_path(@topic)  do |n| %>
	<div class="form-group">
    <%= n.input :description, input_html: { class: "form-control"} %>
	</div>
	<%= n.submit %>
<% end %>